# Generated by Django 4.0.5 on 2022-06-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_timestamp',
            new_name='created_timestamp_UTC',
        ),
    ]
