# Generated by Django 4.0.5 on 2022-06-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('created_timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
