# Generated by Django 4.0.5 on 2022-06-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
